#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

uci -q batch <<-EOF
	set network.5g6.auto=0
	commit network
	
	add_list firewall.@zone[1].network="5g"
	add_list firewall.@zone[1].network="5g6"
	add_list firewall.@zone[0].network="wgc"
	commit firewall
	
	delete dropbear.@dropbear[0].Interface
	commit dropbear

EOF

usbpid=`grep  "Vendor=2cb7" /sys/kernel/debug/usb/devices | awk -F '[= ]' '{print $6}'`
usbpid_fm350=`grep  "Vendor=0e8d" /sys/kernel/debug/usb/devices | awk -F '[= ]' '{print $6}'`

if [ "$usbpid" = "0105" ]; then
#    echo "FM150-AE"
	uci -q batch <<-EOF
		set modemband.@modemband[0].set_port='/dev/ttyUSB2'
		set modemband.@modemband[0].modemid='2cb7:0105'
		commit modemband
		
		set 3ginfo.@3ginfo[0].device='/dev/ttyUSB2'
		commit 3ginfo
		
		set sms_tool_js.@sms_tool_js[0].atport='/dev/ttyUSB2'
		set sms_tool_js.@sms_tool_js[0].readport='/dev/ttyUSB2'
		set sms_tool_js.@sms_tool_js[0].sendport='/dev/ttyUSB2'
		set sms_tool_js.@sms_tool_js[0].ussdport='/dev/ttyUSB2'
		commit sms_tool_js
		
		set luci_statistics.collectd_interface.Interfaces='usb0'
		commit luci_statistics

	EOF
elif [ "$usbpid" = "0a05" ]; then
#    echo "FM650-CN"
	uci -q batch <<-EOF
		set modemband.@modemband[0].set_port='/dev/ttyUSB0'
		set modemband.@modemband[0].modemid='2cb7:0a05'
		
		commit modemband
		
		set 3ginfo.@3ginfo[0].device='/dev/ttyUSB0'
		commit 3ginfo
		
		set sms_tool_js.@sms_tool_js[0].atport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].readport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].sendport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].ussdport='/dev/ttyUSB0'
		commit sms_tool_js
		
		set luci_statistics.collectd_interface.Interfaces='usb0'
		commit luci_statistics

	EOF
elif [ "$usbpid_fm350" = "7127" ]; then
#    echo "FM350-GL"
	uci -q batch <<-EOF
		set modemband.@modemband[0].set_port='/dev/ttyUSB0'
		set modemband.@modemband[0].modemid='0e8d:7127'
		commit modemband
		
		set 3ginfo.@3ginfo[0].device='/dev/ttyUSB0'
		commit 3ginfo
		
		set sms_tool_js.@sms_tool_js[0].atport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].readport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].sendport='/dev/ttyUSB0'
		set sms_tool_js.@sms_tool_js[0].ussdport='/dev/ttyUSB0'
		commit sms_tool_js
		
		set luci_statistics.collectd_interface.Interfaces='eth1'
		commit luci_statistics

	EOF
else
	echo "Unknown"
fi

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
